### PR TITLE
Merge lastest changes to master

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Merge the latest updates into master

> published as @pxblue/react-components@4.1.1

### CODE REVIEW

**Review by huayunh — APPROVED** [review]
Code looks good

**Comment by huayunh** [comment]
I think the infolistitem in react should use black500 for subtitle. Is this a theme thing, or is this a component library thing?

image

**Comment by huayunh** [comment]
Can we change the list item tag to match what's in the DSM? Or is that for the next release?

The latest design is font size 10px, font weight 700, letter-spacing 1px, line-height 16px

**Comment by joebochill** [comment]
Material UI defaults the ListItemText `secondary` value to use `theme.palette.text.secondary`. I just added a fix for it to use textPrimary instead of textSecondary.

The updates to the ILI across frameworks will come in the next release.

**Review by emclaug2 — APPROVED** [review]

**Review by daileytj — APPROVED** [review]

**Pull request merged**
