### PR TITLE
rebrand BLUI -1 version

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes PXBLUE-2501 .

#### Changes proposed in this Pull Request:
- [X] @pxblue => @brightlayer-ui

- [X] PX Blue => Brightlayer UI

- [X] PXBlueDrawer => BLUIDrawer

### CODE REVIEW

**Comment by emclaug2** [comment]
@ektasawant please take a look at this circleci build; it looks like you need to provide a new yarn.lock file.  Maybe delete the old and create a new one?

**Comment by jeffvg** [comment]
also noticing this error for storybook

image

**Comment by emclaug2** [comment]
Storybook build is still failing here; can you look into why?

**Comment by ektasawant** [comment]
Closing PR since build is failing here. https://github.com/pxblue/react-component-library/pull/338

**Comment by ektasawant** [comment]
Closing PR since build is failing here. Created new PR here [338](https://github.com/pxblue/react-component-library/pull/338)

**Pull request closed without merging**
