### PR TITLE
Update components to work with version 6 of the theme

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-XXXX

#### Changes proposed in this Pull Request:
- Update Drawer Header, Scorecard Header, and UserMenu to reflect the updates to version 6 of the themes

To test, you'll need to pull down the latest themes, build them, and manually copy them into the storybook or showcase for the time being.

### CODE REVIEW

**Comment by emclaug2** [comment]
I'm seeing no distinction between nested nav items & nav items in the drawer: 

image

**Comment by joebochill** [comment]
> I'm seeing no distinction between nested nav items & nav items in the drawer:

Did you build manually build the latest theme changes and copy them into storybook node modules? 

Should look like this:
image

**Comment by emclaug2** [comment]
@joebochill  You were right, I didn't manually build the theme; Drawer and Scorecard look fine to me, but ListItemTag story is giving some trouble now: 

image

**Comment by joebochill** [comment]
> @joebochill You were right, I didn't manually build the theme; Drawer and Scorecard look fine to me, but ListItemTag story is giving some trouble now:

There are a number of places I saw where storybook breaks down going from light to dark theme because of hard coded colors that are only suitable for light theme. 

This one was hard coded to a white background, which I thought I swapped to using the paper background color from the theme but it must not have taken. 

It’s probably worth logging an issue to address storybook issues when switching themes. I’d rather not try to tackle them all here if I can help it since it’s not directly tied to the theme changes.

**Review by emclaug2 — APPROVED** [review]

**Comment by joebochill** [comment]
I logged #244 to capture issues when toggling the theme

**Pull request merged**
