### PR TITLE
Feature/codecov

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- add codecov dev dependency
- add codecov orb to circleci and add steps to upload report
- codecov folder structure and set git-ignore

https://app.codecov.io/gh/pxblue/react-component-library

### CODE REVIEW

**Comment by jeffvg** [comment]
the report is missing the components directory in the path for reports. Looking at it now

**Comment by huayunh** [comment]
Are there going to be any fancy Readme badges for code coverage?

**Comment by jeffvg** [comment]
> Are there going to be any fancy Readme badges for code coverage?

yes once we have all the repo's configured and coverage reports look good.
This PR isn't ready yet

**Comment by jeffvg** [comment]
started new branch codecov-updated, closing this one

**Pull request closed without merging**
