### PR TITLE
Update to latest theme and font packages

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Update to latest theme
- Update font import syntax

### CODE REVIEW

**Comment by jeffvg** [comment]
do we need these from Font Source?

image

**Comment by joebochill** [comment]
> do we need these from Font Source?

Context? I have a clean console in the showcase and the storybook and the fonts are correct.

**Comment by jeffvg** [comment]
> > do we need these from Font Source?
> 
> Context? I have a clean console in the showcase and the storybook and the fonts are correct.

Yes this was my console in that screen shot. Maybe it's a windows/chrome thing

**Comment by joebochill** [comment]
> > > do we need these from Font Source?
> > 
> > 
> > Context? I have a clean console in the showcase and the storybook and the fonts are correct.
> 
> Yes this was my console in that screen shot. Maybe it's a windows/chrome thing

Which demo? Which page were you on? What were you doing? Fresh clone?

**Comment by jeffvg** [comment]
> > > > do we need these from Font Source?
> > > 
> > > 
> > > Context? I have a clean console in the showcase and the storybook and the fonts are correct.
> > 
> > 
> > Yes this was my console in that screen shot. Maybe it's a windows/chrome thing
> 
> Which demo? Which page were you on? What were you doing? Fresh clone?



> > > > do we need these from Font Source?
> > > 
> > > 
> > > Context? I have a clean console in the showcase and the storybook and the fonts are correct.
> > 
> > 
> > Yes this was my console in that screen shot. Maybe it's a windows/chrome thing
> 
> Which demo? Which page were you on? What were you doing? Fresh clone?

Guess that would help. lol  I assumed all the changes in this PR are storybook focused but maybe not?
I get the font error messages in storybook. 
Fresh clone.
Start storybook.
Open dev tools in chrome.
Errors are displayed.
I do not see these font error messages on dev branch.

**Comment by joebochill** [comment]
> Guess that would help. lol I assumed all the changes in this PR are storybook focused but maybe not?
> I get the font error messages in storybook.
> Fresh clone.
> Start storybook.
> Open dev tools in chrome.
> Errors are displayed.
> I do not see these font error messages on dev branch.

Are you seeing the same errors in any of the other repositories that I'm updating?

**Comment by joebochill** [comment]
I'm definitely not seeing those errors on my mac. Maybe related to zScalar?

@huayunh @daileytj @emclaug2 anyone else seeing this?

**Comment by emclaug2** [comment]
Checking this out now on my windows machine.

**Comment by jeffvg** [comment]
> I'm definitely not seeing those errors on my mac. Maybe related to zScalar?
> 
> @huayunh @daileytj @emclaug2 anyone else seeing this?

I just verified the same errors on a non-eaton windows pc

**Comment by emclaug2** [comment]
Yep @jeffvg @joebochill I see the same missing resource errors. 

image

**Comment by emclaug2** [comment]
@joebochill  Check out /.storybook/manager-head.html, this looks like the source of the missing font files.

**Comment by joebochill** [comment]
> Are you seeing the same errors in any of the other repositories that I'm updating?

@emclaug2 @jeffvg

**Comment by emclaug2** [comment]
This is a storybook `manager-head.html` issue so only other one I noticed was in the angular-component-library. @joebochill

**Comment by emclaug2** [comment]
Good fix @joebochill , just run prettier and you're good!

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
